sonar.projectKey=sistema_itinerarios
sonar.projectName=AeroRutas - Sistema de Itinerarios Empresariales
sonar.projectVersion=1.0.0

sonar.sources=airport_service,itinerary_service,frontend
sonar.tests=airport_service/tests,itinerary_service/tests

sonar.sourceEncoding=UTF-8
sonar.language=py

sonar.python.coverage.reportPaths=coverage.xml,airport_service/coverage.xml,itinerary_service/coverage.xml
sonar.python.xunit.reportPath=test-results.xml

sonar.exclusions=**/__init__.py,**/migrations/**/*,frontend/assets/**/*,frontend/scripts/**/*

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300

sonar.verbose=true
